# Generated by Django 2.2.1 on 2019-06-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraRegistro', models.DateField()),
                ('estado', models.CharField(max_length=30)),
                ('numeroOnibus', models.IntegerField()),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('suspeitoID', models.IntegerField()),
                ('urlFoto', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='alertas',
        ),
    ]
